vim.g.mapleader = " "

vim.o.number = true
vim.o.relativenumber = true
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.tabstop = 2
vim.o.signcolumn = "yes"
vim.o.cursorline = true
vim.o.clipboard = "unnamedplus"
vim.o.showmode = false
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.wrap = false
vim.o.confirm = true
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.winborder = "rounded"
vim.o.pumborder = "rounded"
