# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# CLI tool for Cloudflare Workers
brew "cloudflare-wrangler"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Deep clean and optimize your Mac
brew "mole"
# Incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Terminal multiplexer
brew "tmux"
# Parser generator tool
brew "tree-sitter-cli"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Voice and text chat software
cask "discord"
# GNU Emacs text editor
cask "emacs-app"
cask "font-iosevka-term-nerd-font"
cask "font-victor-mono"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Music streaming service
cask "spotify"
# Multimedia player
cask "vlc"
# Gecko based web browser
cask "zen"
